In [1]:
import numpy as np

1. Scaler

In [2]:
a = np.array([10])
print(a)
type(a)


[10]


numpy.ndarray

Vector

In [3]:
b = np.array([1,2,3,4,5,6])
type(b)

numpy.ndarray

3.Matrices

In [4]:
c = np.array([[1,2,3,4,5],[2,3,4,5,6]])
# np.matrix()
print(c)
type(c)

[[1 2 3 4 5]
 [2 3 4 5 6]]


numpy.ndarray

4. Array

In [5]:
np.array([1,2,3])

array([1, 2, 3])

upcasting

In [6]:
np.array([1,2,3.1])

array([1. , 2. , 3.1])

In [7]:
a = np.array([1,2,3,4], ndmin=2)

In [8]:
a.ndim
print(a)

[[1 2 3 4]]


In [9]:
print(a)

[[1 2 3 4]]


5. Attr.

In [10]:
c = np.array([[1,2,3,4,5],[2,3,4,5,6],[20,30,40,50.34,60]])

In [11]:
c.shape

(3, 5)

In [12]:
c.size

15

In [13]:
c.dtype

dtype('float64')

In [14]:
c.itemsize

8

In [15]:
c.dtype

dtype('float64')

In [16]:
c

array([[ 1.  ,  2.  ,  3.  ,  4.  ,  5.  ],
       [ 2.  ,  3.  ,  4.  ,  5.  ,  6.  ],
       [20.  , 30.  , 40.  , 50.34, 60.  ]])

6. Accessing

6.1 2D

In [17]:
c = np.array([[1,2,3,4],[3,4,5,2],[5,2,4,5]])
c[1][2]

c[:,2]

array([3, 5, 4])

3D

In [18]:
c = np.random.randint(40, size = (2, 3, 3))
c


array([[[22,  3, 18],
        [21,  5, 38],
        [ 5, 16, 39]],

       [[35, 33, 38],
        [23, 24, 23],
        [ 7, 12,  1]]])

In [19]:
c[:,0:3,1]  

# get 21 9 21 and 8 18 38

c[:,:,1]

c[0,1:3,1:3]

c.ndim

3

# Arange

In [20]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
np.arange(20,0,-2)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(0,10,dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

# Zeros

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# ones

In [24]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# linespace

In [25]:
np.linspace(2,10, num = 3)

array([ 2.,  6., 10.])

In [26]:
np.linspace(2,10, num=5,retstep = True, endpoint=False, dtype= int)

(array([2, 3, 5, 6, 8]), 1.6)

# identity

In [27]:
np.eye(5,5) # creates identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5,k = -1) # diagonal will shift 

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [29]:
np.diag([1,2,4,5,6]) # gives 2d array with diag element as given

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

# full

In [30]:
np.full((10,10),8) # creates 10X10 matrix with all 8 values

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

# stack
Appending

In [50]:
a = np.random.randint(10, size = (3,5))
b = np.random.randint(99, size = (3,5))


In [51]:
c = np.stack((a,b))
c
# c.ndim # should get 2d not 3d

array([[[ 9,  4,  9,  0,  4],
        [ 7,  4,  2,  7,  1],
        [ 0,  0,  2,  1,  9]],

       [[38, 77, 68, 58, 64],
        [69, 26, 52, 35, 80],
        [44, 55, 93, 65, 41]]])

# vstack 

In [54]:
c = np.vstack((a,b))
c
c.ndim

2

# hstack

In [34]:
a = np.random.randint(10, size = (3,5))
b = np.random.randint(99, size = (3,5))

print(a)
print(b)

np.hstack((a,b))

[[8 9 2 5 9]
 [8 9 8 2 2]
 [2 8 6 3 1]]
[[50 86  3 97 10]
 [ 3  7 77 14 78]
 [79 29 36 84  6]]


array([[ 8,  9,  2,  5,  9, 50, 86,  3, 97, 10],
       [ 8,  9,  8,  2,  2,  3,  7, 77, 14, 78],
       [ 2,  8,  6,  3,  1, 79, 29, 36, 84,  6]])

# concatinate

In [35]:
a = np.random.randint(10, size = (3,5))
b = np.random.randint(99, size = (3,5))

print(a)
print(b)

c = np.concatenate((a,b), axis= 0)
c.ndim

[[1 1 2 2 9]
 [4 8 1 6 5]
 [0 9 5 0 8]]
[[56 26 92 29  3]
 [31  5 24 38 74]
 [46 88 91 66 94]]


2

In [36]:
c = np.concatenate((a,b), axis= 1) # corresponding rows of 2 arrays will get concatinated.
c

array([[ 1,  1,  2,  2,  9, 56, 26, 92, 29,  3],
       [ 4,  8,  1,  6,  5, 31,  5, 24, 38, 74],
       [ 0,  9,  5,  0,  8, 46, 88, 91, 66, 94]])

# Random

In [37]:
c = np.random.rand(8,8)
c

array([[0.3798713 , 0.9441287 , 0.27711918, 0.35921552, 0.70335526,
        0.67764048, 0.30494891, 0.55245458],
       [0.14987789, 0.23067312, 0.7968747 , 0.16454518, 0.11347158,
        0.82432182, 0.76847477, 0.54956961],
       [0.88542584, 0.23294232, 0.88752702, 0.978572  , 0.02685711,
        0.63338608, 0.95871396, 0.55151013],
       [0.77910803, 0.96948207, 0.5946048 , 0.11135855, 0.23714942,
        0.30320357, 0.82895805, 0.22623927],
       [0.75045809, 0.29106949, 0.67058506, 0.33731353, 0.94153923,
        0.14684042, 0.70167535, 0.75512852],
       [0.51823315, 0.59511554, 0.44871143, 0.9225462 , 0.73599215,
        0.09190858, 0.42791636, 0.07189183],
       [0.90192742, 0.4437553 , 0.73411695, 0.40789874, 0.00980106,
        0.43168849, 0.36337772, 0.0565582 ],
       [0.45609763, 0.45562246, 0.36622127, 0.10936993, 0.23357499,
        0.92071128, 0.84809247, 0.00177372]])

In [38]:
b = c.reshape((2,2,2,2,2,2))
b.ndim

6

# resize

In [39]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
np.resize(a,(10,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [2, 3, 4, 5],
       [6, 7, 8, 9],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

# Flatten and ravel
Convert only higher dimension to lower dimension.

In [41]:
a = np.random.randint(2,10,size=(10,10,10))
a

array([[[6, 5, 2, 9, 8, 2, 3, 4, 5, 6],
        [7, 6, 6, 8, 8, 8, 6, 4, 8, 3],
        [9, 8, 7, 6, 8, 3, 7, 9, 4, 2],
        [9, 7, 6, 5, 6, 9, 2, 6, 5, 6],
        [6, 6, 9, 7, 5, 2, 2, 5, 4, 7],
        [7, 9, 8, 4, 4, 2, 4, 4, 9, 4],
        [4, 3, 4, 5, 5, 4, 3, 6, 4, 2],
        [4, 9, 2, 3, 2, 6, 4, 9, 6, 5],
        [2, 3, 4, 9, 2, 5, 8, 9, 6, 8],
        [2, 9, 5, 3, 6, 3, 3, 3, 9, 4]],

       [[8, 3, 6, 3, 5, 3, 6, 6, 9, 7],
        [8, 3, 4, 9, 4, 4, 5, 7, 3, 5],
        [5, 2, 6, 6, 8, 6, 6, 9, 6, 8],
        [4, 4, 9, 6, 8, 7, 7, 7, 4, 9],
        [3, 8, 3, 6, 2, 3, 8, 4, 5, 5],
        [3, 7, 6, 8, 5, 8, 7, 2, 3, 2],
        [7, 3, 3, 8, 7, 7, 5, 2, 4, 8],
        [2, 4, 2, 8, 5, 7, 6, 4, 2, 4],
        [4, 4, 8, 2, 9, 9, 4, 6, 2, 7],
        [4, 8, 6, 3, 8, 2, 8, 5, 7, 6]],

       [[8, 9, 7, 7, 9, 3, 6, 4, 9, 5],
        [4, 8, 2, 3, 8, 2, 9, 9, 4, 3],
        [5, 6, 8, 7, 8, 5, 9, 5, 7, 5],
        [2, 6, 7, 9, 8, 7, 9, 7, 9, 3],
        [3, 5, 5, 8, 5, 5, 9, 3, 8, 

In [42]:
a.flatten()


array([6, 5, 2, 9, 8, 2, 3, 4, 5, 6, 7, 6, 6, 8, 8, 8, 6, 4, 8, 3, 9, 8,
       7, 6, 8, 3, 7, 9, 4, 2, 9, 7, 6, 5, 6, 9, 2, 6, 5, 6, 6, 6, 9, 7,
       5, 2, 2, 5, 4, 7, 7, 9, 8, 4, 4, 2, 4, 4, 9, 4, 4, 3, 4, 5, 5, 4,
       3, 6, 4, 2, 4, 9, 2, 3, 2, 6, 4, 9, 6, 5, 2, 3, 4, 9, 2, 5, 8, 9,
       6, 8, 2, 9, 5, 3, 6, 3, 3, 3, 9, 4, 8, 3, 6, 3, 5, 3, 6, 6, 9, 7,
       8, 3, 4, 9, 4, 4, 5, 7, 3, 5, 5, 2, 6, 6, 8, 6, 6, 9, 6, 8, 4, 4,
       9, 6, 8, 7, 7, 7, 4, 9, 3, 8, 3, 6, 2, 3, 8, 4, 5, 5, 3, 7, 6, 8,
       5, 8, 7, 2, 3, 2, 7, 3, 3, 8, 7, 7, 5, 2, 4, 8, 2, 4, 2, 8, 5, 7,
       6, 4, 2, 4, 4, 4, 8, 2, 9, 9, 4, 6, 2, 7, 4, 8, 6, 3, 8, 2, 8, 5,
       7, 6, 8, 9, 7, 7, 9, 3, 6, 4, 9, 5, 4, 8, 2, 3, 8, 2, 9, 9, 4, 3,
       5, 6, 8, 7, 8, 5, 9, 5, 7, 5, 2, 6, 7, 9, 8, 7, 9, 7, 9, 3, 3, 5,
       5, 8, 5, 5, 9, 3, 8, 4, 8, 2, 2, 8, 7, 5, 9, 6, 7, 4, 5, 6, 4, 8,
       9, 2, 2, 4, 5, 8, 3, 5, 6, 2, 3, 9, 6, 8, 4, 2, 3, 8, 8, 6, 5, 6,
       9, 3, 5, 7, 2, 7, 2, 9, 6, 5, 2, 8, 5, 3, 8,

In [43]:
a.ravel() # just view, ref to the parent array.

array([6, 5, 2, 9, 8, 2, 3, 4, 5, 6, 7, 6, 6, 8, 8, 8, 6, 4, 8, 3, 9, 8,
       7, 6, 8, 3, 7, 9, 4, 2, 9, 7, 6, 5, 6, 9, 2, 6, 5, 6, 6, 6, 9, 7,
       5, 2, 2, 5, 4, 7, 7, 9, 8, 4, 4, 2, 4, 4, 9, 4, 4, 3, 4, 5, 5, 4,
       3, 6, 4, 2, 4, 9, 2, 3, 2, 6, 4, 9, 6, 5, 2, 3, 4, 9, 2, 5, 8, 9,
       6, 8, 2, 9, 5, 3, 6, 3, 3, 3, 9, 4, 8, 3, 6, 3, 5, 3, 6, 6, 9, 7,
       8, 3, 4, 9, 4, 4, 5, 7, 3, 5, 5, 2, 6, 6, 8, 6, 6, 9, 6, 8, 4, 4,
       9, 6, 8, 7, 7, 7, 4, 9, 3, 8, 3, 6, 2, 3, 8, 4, 5, 5, 3, 7, 6, 8,
       5, 8, 7, 2, 3, 2, 7, 3, 3, 8, 7, 7, 5, 2, 4, 8, 2, 4, 2, 8, 5, 7,
       6, 4, 2, 4, 4, 4, 8, 2, 9, 9, 4, 6, 2, 7, 4, 8, 6, 3, 8, 2, 8, 5,
       7, 6, 8, 9, 7, 7, 9, 3, 6, 4, 9, 5, 4, 8, 2, 3, 8, 2, 9, 9, 4, 3,
       5, 6, 8, 7, 8, 5, 9, 5, 7, 5, 2, 6, 7, 9, 8, 7, 9, 7, 9, 3, 3, 5,
       5, 8, 5, 5, 9, 3, 8, 4, 8, 2, 2, 8, 7, 5, 9, 6, 7, 4, 5, 6, 4, 8,
       9, 2, 2, 4, 5, 8, 3, 5, 6, 2, 3, 9, 6, 8, 4, 2, 3, 8, 8, 6, 5, 6,
       9, 3, 5, 7, 2, 7, 2, 9, 6, 5, 2, 8, 5, 3, 8,

# Transpose

In [44]:
a = np.arange(10).reshape(5,2)

In [45]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [46]:
np.transpose(a)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])