In [3]:
import numpy as np

1. Scaler

In [4]:
a = np.array([10])
print(a)
type(a)


[10]


numpy.ndarray

Vector

In [5]:
b = np.array([1,2,3,4,5,6])
type(b)

numpy.ndarray

3.Matrices

In [6]:
c = np.array([[1,2,3,4,5],[2,3,4,5,6]])
# np.matrix()
print(c)
type(c)

[[1 2 3 4 5]
 [2 3 4 5 6]]


numpy.ndarray

4. Array

In [7]:
np.array([1,2,3])

array([1, 2, 3])

upcasting

In [8]:
np.array([1,2,3.1])

array([1. , 2. , 3.1])

In [9]:
a = np.array([1,2,3,4], ndmin=2)

In [10]:
a.ndim
print(a)

[[1 2 3 4]]


In [11]:
print(a)

[[1 2 3 4]]


5. Attr.

In [12]:
c = np.array([[1,2,3,4,5],[2,3,4,5,6],[20,30,40,50.34,60]])

In [13]:
c.shape

(3, 5)

In [14]:
c.size

15

In [15]:
c.dtype

dtype('float64')

In [16]:
c.itemsize

8

In [17]:
c.dtype

dtype('float64')

In [18]:
c

array([[ 1.  ,  2.  ,  3.  ,  4.  ,  5.  ],
       [ 2.  ,  3.  ,  4.  ,  5.  ,  6.  ],
       [20.  , 30.  , 40.  , 50.34, 60.  ]])

6. Accessing

6.1 2D

In [19]:
c = np.array([[1,2,3,4],[3,4,5,2],[5,2,4,5]])
c[1][2]

c[:,2]

array([3, 5, 4])

3D

In [20]:
c = np.random.randint(40, size = (2, 3, 3))
c


array([[[ 8, 27,  9],
        [30, 26, 38],
        [ 2, 16, 12]],

       [[ 8, 38, 16],
        [22, 39, 10],
        [18,  8, 20]]])

In [21]:
c[:,0:3,1]  

# get 21 9 21 and 8 18 38

c[:,:,1]

c[0,1:3,1:3]

c.ndim

3

# Arange

In [22]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.arange(20,0,-2)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(0,10,dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

# Zeros

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# ones

In [26]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# linespace

In [27]:
np.linspace(2,10, num = 3)

array([ 2.,  6., 10.])

In [28]:
np.linspace(2,10, num=5,retstep = True, endpoint=False, dtype= int)

(array([2, 3, 5, 6, 8]), 1.6)

# identity

In [29]:
np.eye(5,5) # creates identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(5,k = -1) # diagonal will shift 

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [31]:
np.diag([1,2,4,5,6]) # gives 2d array with diag element as given

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

# full

In [32]:
np.full((10,10),8) # creates 10X10 matrix with all 8 values

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

# stack
Appending

In [33]:
a = np.random.randint(10, size = (3,5))
b = np.random.randint(99, size = (3,5))

In [34]:
c = np.stack((a,b))
c
c.ndim # should get 2d not 3d

3

# vstack 

In [35]:
c = np.vstack((a,b))
c
c.ndim

2

# hstack

In [36]:
a = np.random.randint(10, size = (3,5))
b = np.random.randint(99, size = (3,5))

print(a)
print(b)

np.hstack((a,b))

[[2 0 1 5 1]
 [7 7 4 0 7]
 [9 8 0 7 5]]
[[22 98 78 17 93]
 [27 61 84 52 46]
 [79 36 14 14 72]]


array([[ 2,  0,  1,  5,  1, 22, 98, 78, 17, 93],
       [ 7,  7,  4,  0,  7, 27, 61, 84, 52, 46],
       [ 9,  8,  0,  7,  5, 79, 36, 14, 14, 72]])

# concatinate

In [37]:
a = np.random.randint(10, size = (3,5))
b = np.random.randint(99, size = (3,5))

print(a)
print(b)

c = np.concatenate((a,b), axis= 0)
c.ndim

[[0 5 0 5 1]
 [9 1 2 2 5]
 [5 1 4 0 5]]
[[95 95 70 67 68]
 [49 43 68 65 66]
 [27 74 46 11 86]]


2

In [38]:
c = np.concatenate((a,b), axis= 1) # corresponding rows of 2 arrays will get concatinated.
c

array([[ 0,  5,  0,  5,  1, 95, 95, 70, 67, 68],
       [ 9,  1,  2,  2,  5, 49, 43, 68, 65, 66],
       [ 5,  1,  4,  0,  5, 27, 74, 46, 11, 86]])

# Random

In [39]:
c = np.random.rand(8,8)
c

array([[0.69615183, 0.38635408, 0.44135013, 0.56801695, 0.41320254,
        0.39682255, 0.82867151, 0.12557527],
       [0.59225197, 0.8534369 , 0.43428258, 0.56075044, 0.8618635 ,
        0.26227563, 0.10984939, 0.26328398],
       [0.7601149 , 0.84503204, 0.04511219, 0.12995214, 0.07346385,
        0.17849274, 0.56489067, 0.93638585],
       [0.22790463, 0.39077854, 0.02455866, 0.53342218, 0.30775717,
        0.23291753, 0.24771207, 0.42077824],
       [0.15475003, 0.45793985, 0.19382965, 0.61262689, 0.61048093,
        0.72953499, 0.15981702, 0.45482327],
       [0.18867117, 0.96613216, 0.24948279, 0.37583776, 0.25466132,
        0.16760669, 0.78932606, 0.0477342 ],
       [0.6472515 , 0.47065126, 0.95754122, 0.60229702, 0.94160083,
        0.86614578, 0.46048887, 0.25888597],
       [0.83782343, 0.44462588, 0.38154101, 0.09320639, 0.24457606,
        0.02161295, 0.46300089, 0.91241   ]])

In [ ]:
b = c.reshape((2,2,2,2,2,2))
b.ndim

6

# resize

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
np.resize(a,(10,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [2, 3, 4, 5],
       [6, 7, 8, 9],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

# Flatten and ravel
Convert only higher dimension to lower dimension.

In [61]:
a = np.random.randint(2,10,size=(10,10,10))
a

array([[[9, 5, 6, 8, 7, 6, 8, 7, 9, 6],
        [5, 4, 7, 7, 7, 3, 4, 6, 4, 7],
        [4, 7, 5, 4, 2, 4, 9, 3, 9, 9],
        [5, 9, 4, 3, 4, 5, 4, 5, 2, 2],
        [8, 6, 8, 6, 5, 2, 2, 6, 4, 4],
        [2, 5, 3, 4, 2, 3, 5, 7, 3, 3],
        [6, 3, 3, 2, 9, 2, 8, 9, 8, 7],
        [4, 4, 7, 7, 7, 7, 8, 3, 8, 8],
        [6, 9, 5, 9, 5, 9, 4, 5, 7, 7],
        [7, 2, 8, 2, 7, 4, 4, 9, 2, 6]],

       [[3, 2, 4, 7, 2, 3, 4, 7, 8, 7],
        [7, 8, 8, 2, 5, 2, 4, 3, 5, 7],
        [6, 4, 9, 8, 4, 7, 3, 4, 7, 2],
        [2, 7, 7, 5, 7, 8, 3, 5, 4, 3],
        [4, 7, 4, 9, 2, 5, 8, 4, 3, 7],
        [8, 2, 4, 2, 6, 9, 9, 3, 3, 2],
        [5, 7, 7, 9, 4, 3, 9, 8, 7, 3],
        [9, 6, 9, 7, 6, 6, 3, 5, 6, 8],
        [4, 2, 5, 3, 5, 8, 7, 5, 7, 2],
        [9, 8, 2, 6, 9, 8, 4, 7, 3, 9]],

       [[7, 3, 5, 3, 9, 2, 7, 5, 9, 4],
        [5, 5, 5, 8, 6, 8, 3, 6, 2, 4],
        [2, 7, 8, 9, 2, 6, 8, 6, 2, 9],
        [5, 7, 8, 2, 5, 8, 2, 3, 8, 2],
        [5, 9, 6, 3, 6, 4, 5, 5, 6, 

In [67]:
a.flatten()


array([9, 5, 6, 8, 7, 6, 8, 7, 9, 6, 5, 4, 7, 7, 7, 3, 4, 6, 4, 7, 4, 7,
       5, 4, 2, 4, 9, 3, 9, 9, 5, 9, 4, 3, 4, 5, 4, 5, 2, 2, 8, 6, 8, 6,
       5, 2, 2, 6, 4, 4, 2, 5, 3, 4, 2, 3, 5, 7, 3, 3, 6, 3, 3, 2, 9, 2,
       8, 9, 8, 7, 4, 4, 7, 7, 7, 7, 8, 3, 8, 8, 6, 9, 5, 9, 5, 9, 4, 5,
       7, 7, 7, 2, 8, 2, 7, 4, 4, 9, 2, 6, 3, 2, 4, 7, 2, 3, 4, 7, 8, 7,
       7, 8, 8, 2, 5, 2, 4, 3, 5, 7, 6, 4, 9, 8, 4, 7, 3, 4, 7, 2, 2, 7,
       7, 5, 7, 8, 3, 5, 4, 3, 4, 7, 4, 9, 2, 5, 8, 4, 3, 7, 8, 2, 4, 2,
       6, 9, 9, 3, 3, 2, 5, 7, 7, 9, 4, 3, 9, 8, 7, 3, 9, 6, 9, 7, 6, 6,
       3, 5, 6, 8, 4, 2, 5, 3, 5, 8, 7, 5, 7, 2, 9, 8, 2, 6, 9, 8, 4, 7,
       3, 9, 7, 3, 5, 3, 9, 2, 7, 5, 9, 4, 5, 5, 5, 8, 6, 8, 3, 6, 2, 4,
       2, 7, 8, 9, 2, 6, 8, 6, 2, 9, 5, 7, 8, 2, 5, 8, 2, 3, 8, 2, 5, 9,
       6, 3, 6, 4, 5, 5, 6, 4, 5, 7, 8, 7, 2, 3, 6, 7, 9, 2, 9, 8, 8, 2,
       7, 6, 4, 9, 6, 9, 4, 4, 9, 6, 6, 9, 4, 2, 5, 9, 2, 7, 5, 4, 3, 5,
       5, 6, 4, 6, 2, 2, 3, 2, 6, 4, 9, 3, 4, 3, 6,

In [ ]:
a.ravel() # just view, ref to the parent array.

array([9, 5, 6, 8, 7, 6, 8, 7, 9, 6, 5, 4, 7, 7, 7, 3, 4, 6, 4, 7, 4, 7,
       5, 4, 2, 4, 9, 3, 9, 9, 5, 9, 4, 3, 4, 5, 4, 5, 2, 2, 8, 6, 8, 6,
       5, 2, 2, 6, 4, 4, 2, 5, 3, 4, 2, 3, 5, 7, 3, 3, 6, 3, 3, 2, 9, 2,
       8, 9, 8, 7, 4, 4, 7, 7, 7, 7, 8, 3, 8, 8, 6, 9, 5, 9, 5, 9, 4, 5,
       7, 7, 7, 2, 8, 2, 7, 4, 4, 9, 2, 6, 3, 2, 4, 7, 2, 3, 4, 7, 8, 7,
       7, 8, 8, 2, 5, 2, 4, 3, 5, 7, 6, 4, 9, 8, 4, 7, 3, 4, 7, 2, 2, 7,
       7, 5, 7, 8, 3, 5, 4, 3, 4, 7, 4, 9, 2, 5, 8, 4, 3, 7, 8, 2, 4, 2,
       6, 9, 9, 3, 3, 2, 5, 7, 7, 9, 4, 3, 9, 8, 7, 3, 9, 6, 9, 7, 6, 6,
       3, 5, 6, 8, 4, 2, 5, 3, 5, 8, 7, 5, 7, 2, 9, 8, 2, 6, 9, 8, 4, 7,
       3, 9, 7, 3, 5, 3, 9, 2, 7, 5, 9, 4, 5, 5, 5, 8, 6, 8, 3, 6, 2, 4,
       2, 7, 8, 9, 2, 6, 8, 6, 2, 9, 5, 7, 8, 2, 5, 8, 2, 3, 8, 2, 5, 9,
       6, 3, 6, 4, 5, 5, 6, 4, 5, 7, 8, 7, 2, 3, 6, 7, 9, 2, 9, 8, 8, 2,
       7, 6, 4, 9, 6, 9, 4, 4, 9, 6, 6, 9, 4, 2, 5, 9, 2, 7, 5, 4, 3, 5,
       5, 6, 4, 6, 2, 2, 3, 2, 6, 4, 9, 3, 4, 3, 6,

# Transpose

In [69]:
a = np.arange(10).reshape(5,2)

In [70]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [71]:
np.transpose(a)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])